config/routes.rb
Rails.application.routes.draw do
  get 'tasks/create'

  get 'tasks/update'

  get 'tasks/destroy'

  root to: 'boards#index'

  devise_for :users
  resources :users

  resources :boards do
    resources :tasks do
      member do
        post 'update_status'
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.id?
      can :manage, Board, user_id: user.id
      can :manage, Task

      can :read, Board
    else # Guest
      can :read, Board, :public => true
      can :read, Task
    end
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  scope :public_only, -> { where(:public => true) }

  belongs_to :user
  has_many :tasks

  validates_presence_of :title
  validates_presence_of :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  enum status: [:todo, :inprogress, :toverify, :done]
  enum priority: [:low, :normal, :high, :critical]

  belongs_to :user
  belongs_to :board

  validates_presence_of :user
  validates_presence_of :board
  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      respond_to do |format|
        format.json { head :forbidden }
        format.html { redirect_to root_url, :alert => exception.message }
      end
    else
      respond_to do |format|
        format.json { head :forbidden }
        format.html { redirect_to new_user_session_path, :alert => exception.message }
      end
    end
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  load_and_authorize_resource

  respond_to :html, :json

  def index
    if user_signed_in?
      @boards = Board.all
    else
      @boards = Board.public_only
    end
  end

  def show
    @tasks = @board.tasks.group_by { |t| t.status }

    @task_statuses = Task.statuses
    @task = @board.tasks.new
  end

  def new
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    flash[:notice] = I18n.t 'activerecord.success.success' if @board.save
    respond_with(@board)
  end

  def edit
  end

  def update
    flash[:notice] = I18n.t 'activerecord.success.success' if @board.update_attributes(board_params)
    respond_with(@board)
  end

  def destroy
    flash[:notice] = I18n.t 'activerecord.success.deleted_success' if @board.destroy
    redirect_to root_url
  end

  private

  def board_params
    params.require(:board).permit(:title, :public)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  before_action :set_board

  def create
    @board = Board.find(params[:board_id])
    @task = @board.tasks.build(task_params)
    @task.user = current_user
    if @task.save
      respond_with(@board, @task, status: 201, layout: false)
    else
      @task.errors.full_messages.each do |msg|
      flash[:alert] = msg
      end
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  def update_status
    @task.update_attributes(task_update_status_params)
    respond_with @board, @task
  end

  def destroy
    flash[:notice] = I18n.t 'activerecord.success.deleted_success' if @task.destroy
    respond_with @board
  end

  private

  def set_board
    @board = Board.find(params[:board_id])
  end

  def task_update_status_params
    params.require(:task).permit(:status)
  end

  def task_params
    params.require(:task).permit(:title, :status, :priority)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def beautify_priority(priority)
    color = nil
    case priority
    when 'low'
      color = 'info'
    when 'normal'
      color = 'success'
    when 'high'
      color = 'warning'
    when 'critical'
      color = 'danger'
    end

    "<span class='label label-#{color}'>#{priority}<span>".html_safe
  end
end

app/views/boards/_card.html.haml
.thumbnail.card.card-1
  .caption
    %h4.card-title
      = fa_icon board.public? ? 'unlock' : 'lock'
      = link_to board.title, board_path(board)
    %hr
    %span.small
      = fa_icon 'user'
      By #{board.user.name}

app/views/boards/_form.html.haml
= simple_form_for(@board) do |f|
  = f.input :title
  = f.input :public

  = f.button :submit

app/views/boards/_panel.html.haml
.panel.panel-default.card.card-2
  .panel-heading
    = status
    - if can? :create, Task
      %button.new_task_btn.btn.btn-primary.pull-right.btn-xs{class: "new_task--#{status_id}"}
        = fa_icon "plus", text: "Add #{status} task"
  .panel-body{class: "panel-column panel-statuses-#{status_id}"}
    - if can? :create, Task
      .thumbnail.card.card-2.card--padding.card--task-form
        = render 'tasks/form', status_id: status_id
    %div{class: ('tasks_list' if user_signed_in?), "data-status" => status_id}
      - if tasks.present?
        - tasks.each do |task|
          = render 'tasks/card', task: task

app/views/boards/edit.html.haml
%h1 Boards#edit
%p Find me in app/views/boards/edit.html.haml

= render 'form'

app/views/boards/index.html.haml
.container-fluid
  .row
    .col-md-10
      - if user_signed_in?
        %h1 Everyone boards (public and private)
      - else
        %h1 Everyone public boards
    .col-md-2
      - if can? :create, Board
        = link_to fa_icon("plus", text: "New board"), new_board_path, class: 'btn btn-primary pull-right new-board-button'

  %hr

  .row
    - @boards.each do |board|
      .col-md-3
        = render 'card', board: board

app/views/boards/new.html.haml
.container-fluid
  .row
    .col-md-6.col-md-offset-3
      %h1 Create new board
      .panel.card
        .panel-body
          = render 'form'

app/views/boards/show.html.haml
.container-fluid
  %h2
    = @board.title
    - if can? :manage, @board
      %span.small
        = link_to fa_icon('trash', text: 'Delete board'), board_path(@board), :method => :delete, class: 'delete-board pull-right text-danger', :data => { confirm: I18n.t('helpers.destroy.sure') }

  .clearfix

  %hr
  = render 'layouts/error_messages', object: @task
  .row
    .col-md-3
      = render 'panel', status: 'To Do', status_id: "todo", tasks: @tasks["todo"]
    .col-md-3
      = render 'panel', status: 'In Progress', status_id: "inprogress", tasks: @tasks["inprogress"]
    .col-md-3
      = render 'panel', status: 'To Verify', status_id: "toverify", tasks: @tasks["toverify"]
    .col-md-3
      = render 'panel', status: 'Done', status_id: "done", tasks: @tasks["done"]

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
 <div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
 <ul>
  <% object.errors.full_messages.each do |msg| %>
   <li>* <%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li
    = link_to('Sign out', destroy_user_session_path, :method => :delete)
- else
  %li
    = link_to('Sign in', new_user_session_path, class: 'btn btn-purple btn-xs')
  %li
    = link_to('Sign up', new_user_registration_path, class: 'btn btn-purple btn-xs')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Board'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Hugo Board'}"}
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:400,100,700,500'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/tasks/_card.html.haml
.thumbnail.card.card-1{class: "task-card task-#{task.id}", "data-status": task.status, "data-id": task.id, "data-board-id": task.board_id}
  .caption.task-handler
    %h4.card-title= task.title
    %hr
    %h4
      = beautify_priority task.priority

      - if can? :destroy, task
        = link_to fa_icon('trash', text: 'Delete task'), board_task_path(@board, task), :method => :delete, class: 'pull-right text-danger', :data => { confirm: I18n.t('helpers.destroy.sure') }
    %clearfix
    %span.small
      = fa_icon 'user'
      By #{task.user.name}

app/views/tasks/_form.html.haml
= simple_form_for [@board, @task], remote: true, html: { id: "new_task_#{status_id}" } do |f|
  = f.input :title
  = f.input :priority, default: 0
  = f.input :status, as: :hidden, input_html: { value: status_id }
  = f.button :submit

app/views/tasks/create.html.haml
= render 'card', task: @task

app/views/tasks/new.html.haml
= render 'form'

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>